### ISSUE TITLE
Add more detail on readme

### ISSUE THREAD

**Issue by BajanVlogs** [FreakingDev/ModBanSystem#2]

**Comment by BajanVlogs** [comment]
Like this
Auto PermBan if player gets 7-Days (168 Hours) Total bans

**Comment by BajanVlogs** [comment]
7 total bans?
Or 7 total warns

**Comment by FreakingDev** [comment]
Everytime player gets banned it will save the total hours of it.

7 Days = 168 Hours

So if player gets 7-Days (168Hours) of Total Ban, player will be permanently ban

**Comment by BajanVlogs** [comment]
Ok thanks for the understanding

**Comment by BajanVlogs** [comment]
Also can u add me back on discord 

KevinMCPE#4751
